### ISSUE TITLE
Google auth can't read the QR code.

### ISSUE THREAD

**Issue by cosmos-sajal** [SiliconJungles/eqrcode#10]
I am trying to generate 2FA QR code from my application, the numerical code works perfectly when I enter it manually in google authenticator app.
But when I generate the QR code and scans the same from google auth it gives an error as -
`Cannot interpret QR code.`

I tried scanning the same QR code in other QR scanner apps and it gives me back the 2FA code perfectly.

Can someone please help?

**Comment by cosmos-sajal** [comment]
@nthock can you please help here?

**Comment by nthock** [comment]
I am not too sure how to begin to help here given that the you can get back the same 2FA code perfectly when using other QR scanner apps.

Can you try using other online QR code generator for your input and check if your Google Auth app can recognise it?

**Comment by nthock** [comment]
Hi @cosmos-sajal, there are some major changes since you open this issue. If you are still using this package, you can try upgrading it 0.1.9 and see if it still persists. I will close this issue for now.
