### ISSUE TITLE
Compiler warning

### ISSUE THREAD

**Issue by florish** [SiliconJungles/eqrcode#18]
Not sure how serious this is in practice, but right after adding `eqrcode` (v0.1.8) to a project, this compiler warning popped up:

```
==> eqrcode
Compiling 10 files (.ex)
warning: this clause cannot match because a previous clause at line 33 always matches
  lib/eqrcode/galois_field.ex:33
```

Thought it could be helpful to post this here.

**Comment by nthock** [comment]
Should be fixed by #19
