### ISSUE TITLE
Max length of content is too low

### ISSUE THREAD

**Issue by victorolinasc** [SiliconJungles/eqrcode#5]
Hi! Awesome library! Thanks for your work!

I was wondering if the content max length limit could be raised. This is a blocker for me. Although we should have some limit, 155 is too low for something like OTPs. The following must be present:

otpauth://totp/{authorithy}?secret={base32 encoded secret}&digits=6&period=30&issuer={issuer}

Anyway, this follows the parameters in the spec: https://tools.ietf.org/html/rfc6238

Thanks for your time.

**Comment by nthock** [comment]
Hi @victorolinasc,

We are not able to raise the content max length limit as the algorithm we used do not allow input more than 154 characters.

I am not familiar with the OTP spec, but are you able to use link shorteners for it? If not, then eqrcode would not be able to help you.

**Comment by victorolinasc** [comment]
In OTP, the URI is not a browser navigable URL but a way to transmit data. Unfortunately we can't shorten it in anyway. 

I'll close this. Thanks for sharing the rationale.

**Comment by iwarshak** [comment]
@nthock which algorithm are referring to?

**Comment by nthock** [comment]
@iwarshak This is no longer an issue with the latest version.
