### ISSUE TITLE
Error with trying to encode the value "funny" to PNG.

### ISSUE THREAD

**Issue by jessek1** [SiliconJungles/eqrcode#6]
Other values seem to work fine, we randomly stumbled across this in our tests.  Without having explored the issue, I don't know if the issue is limited to just this one scenario or if others can trigger it.

1) test getting a qr code binary output (ProgPack.Services.Ads.QRCodeServiceTest)
     test/services/ads/qr_code_service_test.exs:9
     ** (FunctionClauseError) no function clause matching in EQRCode.PNG.module_pixels/2

     The following arguments were given to EQRCode.PNG.module_pixels/2:

         # 1
         nil

         # 2
         %{color: <<0, 0, 0>>, module_size: 11}

     Attempted function clauses (showing 2 out of 2):

         defp module_pixels(-0-, %{module_size: module_size})
         defp module_pixels(-1-, %{color: color, module_size: module_size})

     code: data = QRCodeService.get_qr_code("funny", into: :binary)
     stacktrace:
       (eqrcode) lib/eqrcode/png.ex:84: EQRCode.PNG.module_pixels/2
       (elixir) lib/enum.ex:1327: Enum."-map/2-lists^map/1-0-"/2
       (elixir) lib/enum.ex:1327: Enum."-map/2-lists^map/1-0-"/2
       (eqrcode) lib/eqrcode/png.ex:78: EQRCode.PNG.row_pixels/2
       (elixir) lib/stream.ex:565: anonymous fn/4 in Stream.map/2
       (elixir) lib/enum.ex:3317: Enumerable.List.reduce/3
       (elixir) lib/stream.ex:1568: Enumerable.Stream.do_each/4
       (elixir) lib/enum.ex:3015: Enum.join/2
       (eqrcode) lib/eqrcode/png.ex:70: EQRCode.PNG.pixels/2
       (eqrcode) lib/eqrcode/png.ex:38: EQRCode.PNG.png/2
       test/services/ads/qr_code_service_test.exs:10: (test)

**Comment by nthock** [comment]
Hi @jessek1, thanks for raising this issue. Version 0.1.6 should have fix this problem.
