### ISSUE TITLE
Why is there a limit on chars allowed

### ISSUE THREAD

**Issue by badazz91** [SiliconJungles/eqrcode#7]
Hello, 

I am trying to encode vcard-data as a qr code using this eqrcode lib. 

And I was wondering why there is a limitation on maximum size of the input?

```  
def encode(bin) when byte_size(bin) <= 154 do
```

Problem is that vcards can get quite big, or am I missing something? Thank you.

**Comment by robd91** [comment]
Oh I am sorry #5 already explains this. I will close this.
