### ISSUE TITLE
issue with custom pattern

### ISSUE THREAD

**Issue by benonymus** [SiliconJungles/eqrcode#8]
Hey it seems that the custom pattern encoding doesn't really work, other than empty space.
or, what is more likely is that I am not doing it right, but there is almost no info on that.
I tried the example from here:
https://github.com/sunboshan/qrcode
but it does't really look like that at the end for me.
I would liek to know that what is the process to put text as custom patter, I tried to convert text to binary and use that but that doesn't seem to do much.
Also how would i put a logo in it?
Either the image or as part of the pattern?

Thank you

**Comment by nthock** [comment]
Hi there, we are not supporting custom pattern in this package for now.

If you want to put a logo or image, I recommend to do it outside of this package, and ensure that the reader can still encode the QR code.
