### ISSUE TITLE
Add support to change QR-code backgorund color

### ISSUE THREAD

**Issue by vbaranov** [SiliconJungles/eqrcode#9]
We're implementing dark mode for our web application. It would be awesome to have a possibility to invert colours.

**Comment by nthock** [comment]
Thanks for the suggestion. 

I believe the implementation should allow the setting the background color, i.e. the white color portions of the QR code. Then it is up to your application to decide when to change the background color.

Currently we are busy with our existing projects. Pull requests are welcomed for changing the background colours.

**Comment by causztic** [comment]
I'll give this a try!
